-- Baseline ReelShort taxonomy used by the import flow and admin tag picker.
-- Keep translations intact when reapplying the migration; English is canonical.
INSERT INTO "drama_tag_labels" ("key", "nameEn", "nameZh", "nameFr", "createdAt", "updatedAt")
VALUES
  ('Business', 'Business', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Step-Siblings', 'Step-Siblings', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Reverse Harem', 'Reverse Harem', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Age Gap', 'Age Gap', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Campus Lovers', 'Campus Lovers', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Mistaken Identity', 'Mistaken Identity', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Super Power', 'Super Power', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Surrogate Bride', 'Surrogate Bride', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Hidden Feelings', 'Hidden Feelings', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Group Favorite', 'Group Favorite', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Karma', 'Karma', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Self-growth', 'Self-growth', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('First Love', 'First Love', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Genius Babies', 'Genius Babies', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Love-Hate', 'Love-Hate', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Friendship', 'Friendship', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Neighbors', 'Neighbors', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Rebirth', 'Rebirth', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Blind Date', 'Blind Date', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Fake Pregnancy', 'Fake Pregnancy', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Morals & Ethics', 'Morals & Ethics', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Adventure', 'Adventure', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Harem', 'Harem', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Reincarnation', 'Reincarnation', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Taboo', 'Taboo', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Hidden Identity', 'Hidden Identity', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Flash Marriage', 'Flash Marriage', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Redemption', 'Redemption', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Revenge', 'Revenge', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Secret', 'Secret', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Contract Lovers', 'Contract Lovers', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Fake Relationship', 'Fake Relationship', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Love After Marriage', 'Love After Marriage', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Pregnancy', 'Pregnancy', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Enemies to Lovers', 'Enemies to Lovers', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Office Romance', 'Office Romance', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Friends to Lovers', 'Friends to Lovers', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Affair', 'Affair', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Reunion', 'Reunion', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Time Travel', 'Time Travel', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('All-Too-Late', 'All-Too-Late', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Love After Divorce', 'Love After Divorce', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Love Triangle', 'Love Triangle', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Fated Lovers', 'Fated Lovers', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Lost Child', 'Lost Child', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('The Chosen One', 'The Chosen One', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Multiple Identities', 'Multiple Identities', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Playing Dumb', 'Playing Dumb', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Cultural Communication', 'Cultural Communication', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT ("key") DO UPDATE
SET
  "nameEn" = EXCLUDED."nameEn",
  "updatedAt" = CURRENT_TIMESTAMP;
